<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <!--<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <DocumentationFile>..\ManualDocViewer\$(AssemblyName).xml</DocumentationFile>-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Img\Components\**" />
    <EmbeddedResource Remove="Img\Components\**" />
    <None Remove="Img\Components\**" />
    <Page Remove="Img\Components\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Img\Burger.png" />
    <None Remove="Img\CatalogueButton.png" />
    <None Remove="Img\ClipBoardButton.png" />
    <None Remove="Img\Component\Amarberry.png" />
    <None Remove="Img\Component\Basic_Kibble.png" />
    <None Remove="Img\Component\Citronal.png" />
    <None Remove="Img\Component\Cooked_Fish_Meat.png" />
    <None Remove="Img\Component\Cooked_Meat.png" />
    <None Remove="Img\Component\Cooked_Meat_Jerky.png" />
    <None Remove="Img\Component\Exceptional_Kibble.png" />
    <None Remove="Img\Component\Extraordinary_Kibble.png" />
    <None Remove="Img\Component\Fiber.png" />
    <None Remove="Img\Component\Focal_Chili.png" />
    <None Remove="Img\Component\Giant_Bee_Honey.png" />
    <None Remove="Img\Component\Lazarus_Chowder.png" />
    <None Remove="Img\Component\Longrass.png" />
    <None Remove="Img\Component\Mejoberry.png" />
    <None Remove="Img\Component\Narcoberry.png" />
    <None Remove="Img\Component\Narcotics.png" />
    <None Remove="Img\Component\Prime_Meat_Jerky.png" />
    <None Remove="Img\Component\Rare_Flower.png" />
    <None Remove="Img\Component\Rare_Mushroom.png" />
    <None Remove="Img\Component\Regular_Kibble.png" />
    <None Remove="Img\Component\Rockarrot.png" />
    <None Remove="Img\Component\Sap.png" />
    <None Remove="Img\Component\Savoroot.png" />
    <None Remove="Img\Component\Simple_Kibble.png" />
    <None Remove="Img\Component\Spoiled_Meat.png" />
    <None Remove="Img\Component\Superior_Kibble.png" />
    <None Remove="Img\Component\Tintoberry.png" />
    <None Remove="Img\Dinosaure\Allosaurus.png" />
    <None Remove="Img\Dinosaure\Ankylosaurus.png" />
    <None Remove="Img\Dinosaure\Araneo.png" />
    <None Remove="Img\Dinosaure\Argentavis.png" />
    <None Remove="Img\Dinosaure\Baryonyx.png" />
    <None Remove="Img\Dinosaure\Basilosaurus.png" />
    <None Remove="Img\Dinosaure\Brontosaurus.png" />
    <None Remove="Img\Dinosaure\Carbonemys.png" />
    <None Remove="Img\Dinosaure\Carnotaurus.png" />
    <None Remove="Img\Dinosaure\Daeodon.png" />
    <None Remove="Img\Dinosaure\Dilophosaur.png" />
    <None Remove="Img\Dinosaure\Diplodocus.png" />
    <None Remove="Img\Dinosaure\Dodo.png" />
    <None Remove="Img\Dinosaure\Dunkleosteus.png" />
    <None Remove="Img\Dinosaure\Giganotosaurus.png" />
    <None Remove="Img\Dinosaure\Kentrosaurus.png" />
    <None Remove="Img\Dinosaure\Mammoth.png" />
    <None Remove="Img\Dinosaure\Megalodon.png" />
    <None Remove="Img\Dinosaure\Mosasaurus.png" />
    <None Remove="Img\Dinosaure\Parasaur.png" />
    <None Remove="Img\Dinosaure\Pteranodon.png" />
    <None Remove="Img\Dinosaure\Quetzal.png" />
    <None Remove="Img\Dinosaure\Raptor.png" />
    <None Remove="Img\Dinosaure\Rex.png" />
    <None Remove="Img\Dinosaure\Sarco.png" />
    <None Remove="Img\Dinosaure\Spinosaurus.png" />
    <None Remove="Img\Dinosaure\Stegosaurus.png" />
    <None Remove="Img\Dinosaure\Triceratops.png" />
    <None Remove="Img\Dinosaure\Tusoteuthis.png" />
    <None Remove="Img\Dinosaure\Yutyrannus.png" />
    <None Remove="Img\MemoButton.png" />
    <None Remove="Img\NoteBookButton.png" />
    <None Remove="Img\Reload.png" />
    <None Remove="Img\SearchButton.png" />
    <None Remove="Img\User.png" />
    <None Remove="JSON\Dinosaure.json" />
    <None Remove="JSON\Kibble.json" />
    <None Remove="JSON\Narcotic.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="JSON\Dinosaure.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="JSON\Kibble.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="JSON\Narcotic.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Img\Burger.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\ClipBoardButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeckoDexModelsLibrary\GeckoDexModelsLibrary.csproj" />
    <ProjectReference Include="..\GeckoDexTamingLibrary\GeckoDexTamingLibrary.csproj" />
    <ProjectReference Include="..\GeckoDexUserManager\GeckoDexUserManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Img\CatalogueButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Amarberry.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Basic_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Citronal.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Cooked_Fish_Meat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Cooked_Meat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Cooked_Meat_Jerky.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Exceptional_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Extraordinary_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Fiber.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Focal_Chili.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Giant_Bee_Honey.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Lazarus_Chowder.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Longrass.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Mejoberry.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Narcoberry.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Narcotics.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Prime_Meat_Jerky.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Rare_Flower.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Rare_Mushroom.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Regular_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Rockarrot.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Sap.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Savoroot.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Simple_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Spoiled_Meat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Superior_Kibble.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Component\Tintoberry.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Allosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Ankylosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Araneo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Argentavis.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Baryonyx.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Basilosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Brontosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Carbonemys.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Carnotaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Daeodon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Dilophosaur.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Diplodocus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Dodo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Dunkleosteus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Giganotosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Kentrosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Mammoth.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Megalodon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Mosasaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Parasaur.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Pteranodon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Quetzal.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Raptor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Rex.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Sarco.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Spinosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Stegosaurus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Triceratops.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Tusoteuthis.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Dinosaure\Yutyrannus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\MemoButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\NoteBookButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\Reload.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\SearchButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\User.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
