<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <DocumentationFile>..\ManualDocViewer\$(AssemblyName).xml</DocumentationFile>-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeckoDexModelsLibrary\GeckoDexModelsLibrary.csproj" />
  </ItemGroup>

</Project>
